### ISSUE TITLE
</head>

### ISSUE THREAD

**Issue by imapirate** [gregdaynes/Geode#1]
missing in _head.mobile.html

**Comment by gregdaynes** [comment]
I have a few reasons for this.
• html4/5 does not require closing tags on most things. <head> included
• flexibility - if you add </head> to either of the head files, you have to edit it to add files - if you have a lot of page specific things to add to the <head> that don't apply to another page - this sucks. 



  // add all the stuff you want to this page specifically here - still in the head, but not on other pages

// you could add </head> here but it's not required.
<body>
